### ISSUE TITLE
[Feature Request] Add Button to Clear Local Cache of Star History

### ISSUE THREAD

**Issue by redfire75369** [probablykasper/starchart#1]
Currently, the history is stored in local storage. This means that if the data gets updated, it won't get automatically fetched. Although this is fine, there should be an option to refresh it manually, so one doesn't need to remove the repo and then add it back.

**Comment by kasper9n** [comment]
I think re-adding it is fine tbh. The cache is also ignored after 2 days so it doesn't get too stale
