### ISSUE TITLE
Put repo names in url?

### ISSUE THREAD

**Issue by boxed** [probablykasper/starchart#2]
I like this project much more than star-history.com because of the higher resolution and better interaction, but star-history puts the repos in the url so you can share URLs with people which this project lacks. I think that's a killer feature.

**Comment by kasper9n** [comment]
It would be nice, but would kinda need a server to store the star history. I don't expect to spend time on that, though a PR would be welcome

**Comment by boxed** [comment]
That's not what I meant. Just put the things the user select into the URL with https://developer.mozilla.org/en-US/docs/Web/API/Location/replace or https://developer.mozilla.org/en-US/docs/Web/API/Location/assign It's a fully client side thing. That's what star-history does.

**Comment by kasper9n** [comment]
Fair enough I suppose, just thought it would we weird to link to it when it might take so long to load. Feel free to submit a PR!

**Comment by boxed** [comment]
Oh. Hmm. Yea ok, that's a good point.
